[package]
name = "native-windows-gui"
version = "0.0.1"
authors = ["Gabriel Dube <gdube.475@gmail.com>"]

[dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"
user32-sys = "0.2.0"
comctl32-sys = "0.2.0"