[package]
name = "native-windows-derive"
version = "0.1.0"
authors = ["gdube <gdube.475@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full"]}
quote = "1.0"
